---
R2:
  hostname: 192.168.1.151
  platform: cisco_ios
  port: 22
  username: kondo
  password: cisco
  groups:
    - cisco_group
SW2:
  hostname: 192.168.1.161
  platform: cisco_ios
  port: 22
  username: kondo
  password: cisco
  groups:
    - cisco_group
